### ISSUE TITLE
Allow for single section for all PRs

### ISSUE THREAD

**Issue by morluna** [spring-io/github-release-notes-generator#74]
Our team is currently small and have opted to use emojis (https://gitmoji.dev/) in the PR title instead of using labels. It would be great to be able to to have a single section of release notes with all the PRs associated for that milestone. 

Example:
```
Changed PRs:
- ✨ Awesome new feature [#37](https://github.com/....)
- 🐛 Fix bug [#38](https://github.com/....)
```

Unless I'm missing something, it seems that this isn't possible at the moment. It would be nice to define our config file like:
```
changelog:
  sections:
  - title: "Changed PRs"
    labels: ["*"]
```
